### ISSUE TITLE
Function RGB2FloatArray does not accept Array{RGB{Float64},1}

### ISSUE THREAD

**Issue by chaseleslie** [peterkovesi/PerceptualColourMaps.jl#23]
Minimal example:

```julia
RGB2FloatArray(RGB{Float64}[RGB(1,0,0), RGB(0,1,0), RGB(0,0,1)])
```
yields the following error:

> ERROR: MethodError: no method matching RGB2FloatArray(::Array{RGB{Float64},1})
Closest candidates are:
  RGB2FloatArray(::Array{RGBA{Float64},1}) at /home/../.julia/packages/PerceptualColourMaps/60SCf/src/cmap.jl:2637
Stacktrace:
 [1] top-level scope at REPL[18]:1

`RGB2FloatArray` is called when passing an array of RGB to `equalisecolourmap`.

Using PerceptualColourMaps v0.3.3

**Comment by peterkovesi** [comment]
Thanks for that. Looks like it was a long standing cut and paste error!  Fixed now on master.
