### ISSUE TITLE
v.0.3.4 not registered

### ISSUE THREAD

**Issue by CarolusMagnus** [peterkovesi/PerceptualColourMaps.jl#25]
Version 0.3.4 seems not to be registered. At least I cannot install it:
```
add PerceptualColourMaps@0.3.4
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package PerceptualColourMaps [54e51dfa]:
 PerceptualColourMaps [54e51dfa] log:
 ├─possible versions are: 0.3.0-0.3.3 or uninstalled
 └─restricted to versions 0.3.4 by an explicit requirement — no versions left
```

**Comment by peterkovesi** [comment]
Ok thanks for the info, looks like there is a registration issue.  I also
need to tag a new version for some small bug fixes. Unfortunately  I am
away from my machine until Tuesday. In the meantime perhaps try installing
#master

**Comment by peterkovesi** [comment]
Hopefully all is resolved now.  Things were a bit messed up so I deleted tag0.3.4 and made it point to the current master and registered it.
Let me know if you still have any problems

**Comment by CarolusMagnus** [comment]
For me it is working now as it should.
