### ISSUE TITLE
PerceptualColourMaps pins down ImageCore and a few others

### ISSUE THREAD

**Issue by ederag** [peterkovesi/PerceptualColourMaps.jl#33]
`PerceptualColourMaps` is still pinning down `ImageCore` and others, just like in #32.

```julia
pkg> add PerceptualColourMaps
  [54e51dfa] + PerceptualColourMaps v0.3.5
...
  [a09fc81d] ↓ ImageCore v0.9.4 ⇒ v0.8.22
  [82e4d734] ↓ ImageIO v0.6.6 ⇒ v0.4.1
  [9b13fd28] ↓ IndirectArrays v1.0.0 ⇒ v0.5.1
  [a98d9a8b] ↓ Interpolations v0.14.4 ⇒ v0.13.6
  [f09324ee] ↓ Netpbm v1.0.2 ⇒ v1.0.1
...
```

Needs to be released (v0.3.5 seems to be the latest), for the fix to be widely available ?

**Comment by peterkovesi** [comment]
Oh dear!!  Sorry about that.  I have just made a new release hopefully all is well now.

**Comment by ederag** [comment]
Indeed, it is fixed, thanks !
