### ISSUE TITLE
Include color scales directly in Plots

### ISSUE THREAD

**Issue by mkborregaard** [peterkovesi/PerceptualColourMaps.jl#4]
Hi, 
these color scales are great. I think it'd be nice to incorporate the short-named subset of these more closely into Plots, which now has an inbuilt system for handling color libraries, and I've opened a PR to do this https://github.com/JuliaPlots/PlotUtils.jl/pull/9

This would make all of the named ramps available simply by e.g. `heatmap(rand(30,30), color = :coolwarm)`, and a user could also load this as his default "color library" in Plots. Such direct integration would require just copying the rgb-values as I do in the PR, rather than depending on this package, as we are trying to keep Plots relatively dependency-light.

The documentation will have its 'color' page expanded, and that page would credit your "good colormaps" paper, and also mentioned that more powerful support for the gradients are available from this package.

However, we will of course only do this if you are on board with it! What  do you say - does it sound like a good idea?

**Comment by peterkovesi** [comment]
That sounds great, yes, go for it.  

The naming I gave the colour maps has been a failure.  While they are systematic they are too long and impossible to remember, and I never use them!   One issue we may have is name clashes.  I can imagine having a number of colour map libraries each with a map called 'heat', 'rainbow' etc.  Perhaps have a naming scheme along the lines of  library_name.colour_map_name ?

Yes, using raw RGB values would be good. I have been meaning to provide arrays of raw RGB values of the colour maps.  It is silly to be constantly recomputing the colour maps from scratch as I have it now.  

My package has been in need of some maintenance and updating for some time but I have been having trouble finding the time to do this.  I am travelling at the moment but I should be back on deck to do something towards the end of next week.  This is probably the kick that I need.

**Comment by mkborregaard** [comment]
Thanks a lot, that is great. I really like the color ramps. I got the RGB values from the web site, except for "fire", which I got from the Bokeh repo.
With regards to name clashes, Plots (master) handles that by letting the user set the current library (`clibrary(:colorcet)`). You can always call a gradient by e.g. `:rainbow`, but if there is a name clash, Plots will choose the version from your current library. Name clashes were the name does not exist in your current library will return one of them along with a descriptive warning message. There is also the slightly more verbose form `cgrad(:fire, :colorcet)` if you want to be sure (e.g. for non-interactive use). Color libraries are also smart for exploration - `showlibrary(:colorcet)` will show all gradients in that library. You can append _r to automatically reverse the gradient (`:kgy_r`).
 Sorry if I got carried away in listing features :-)

My idea is that the user should be able to set his default colorlibrary (and default sequential and diverging gradients) in the .juliarc file and then not have to worry about it again.

Anyway, thanks a lot for this and for your great work with these colormaps.

**Comment by mkborregaard** [comment]
Btw would "colorcet" be the right name for this library?

**Comment by peterkovesi** [comment]
Great that you have the RGB values and great that you have "fire" from the Bokeh repo.  I spent some time at the prodding of James Bednar to tweak the heat colour map and make it a bit better.  The tweaked map has yet to make its way back into the PerceptualColourMaps package...

I guess "colorcet" is the appropriate name.  Keeps things consistent with the Bokeh repo.

Plots has some nice features.  This will make navigating collections of colour maps so much better.

**Comment by mkborregaard** [comment]
Thanks! Let me know if you have any opinion on what should be the default gradients - right now it is fire and coolwarm.

**Comment by peterkovesi** [comment]
Here's my list of colour maps that I think are likely to be of wide use

Linear Maps:
* grey/gray   
* fire
* linear_bgyw_15-100_c67_n256  (BlueGreenYellowWhite, can you think of a better name?) This not too different from MATLAB's 'parula' but avoids IP issues with Mathworks who have indicated that parula is not free to be copied.

Diverging Maps:
* coolwarm

Rainbow Maps:
* rainbow (rainbow_bgyr_35-85_c72_n256)  Rainbow map with good perceptual uniformity.
* rainbowdiverging (diverging-rainbow_bgymr_45-85_c67_n256) Rainbow map that can also be used as a diverging map with yellow as the reference centre colour.

Cyclic Maps:
* phase4 (cyclic_mygbm_30-95_c78_n256) A good cyclic map with four distinct colours allowing four orientations or phase angles to be visualised
* phase2 (cyclic_wrwbw_40-90_c42_n256) A blue - white - red cyclic map for when you are only interested in phase being +ve or -ve.

**Comment by waldyrious** [comment]
> linear_bgyw_15-100_c67_n256 (BlueGreenYellowWhite, can you think of a better name?) This not too different from MATLAB's 'parula' but avoids IP issues with Mathworks who have indicated that parula is not free to be copied.

Why not use [Viridis](http://matplotlib.org/examples/color/colormaps_reference.html)? Parula, besides the IP issues, still has [quite some variability in perceived lightness](https://github.com/BIDS/colormap/blob/gh-pages/index.md#parula), while Viridis was specifically made to be perceptually uniform.

**Comment by mkborregaard** [comment]
The bgyw (IMHO that name works) does not suffer from Parula's problems - these color maps are at least on a par with the default matplotlib ones perceptually. The whole world doesn't have to use viridis (but if one wants it it is in the default color library of e.g. Plots and PyPlot), but the whole world should use perceptually uniform ones. This is actually the root cause of my efforts on PlotUtils, and, dare I assume, @peterkovesi 's efforts here.

**Comment by mkborregaard** [comment]
Species richness of the world's amphibians in 1x1 lat-long squares:
viridis:
<img width="782" alt="skaermbillede 2017-03-19 kl 11 34 31" src="https://cloud.githubusercontent.com/assets/8429802/24080098/277d59ce-0c98-11e7-96f5-79df96e5c7e7.png">
bgyw
<img width="790" alt="skaermbillede 2017-03-19 kl 11 34 13" src="https://cloud.githubusercontent.com/assets/8429802/24080100/2fb06104-0c98-11e7-9ebe-8162cfddcacd.png">
